FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    pkg-config libgtk-3-dev libx11-dev libxi-dev libxrandr-dev libxcursor-dev \
    libwayland-dev libxkbcommon-dev libasound2-dev libudev-dev && \
    rm -rf /var/lib/apt/lists/*

